In [215]:
import pandas as pd
from datetime import datetime, timedelta

In [216]:
df_customers = pd.read_csv('archive/olist_customers_dataset.csv',low_memory=False)
df_customers=df_customers[['customer_id', 'customer_unique_id','customer_city','customer_state']]

In [217]:
df_order =pd.read_csv('archive/olist_orders_dataset.csv',low_memory=False)

df_order

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [218]:
list_colum = ['order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date']

def transformation_en_date(df,list_colum):
       for col in list_colum:
              df[col] =pd.to_datetime(df[col])
              df[col] = df[col].dt.date
       return df

def ajouter_colonne_delais(df,colonne_A,colonne_B):
       df['delais_livraison'] = df['colonne_B'] - df['colonne_A']
       return df

transformation_en_date(df_order,list_colum)

df_order['delai_livraison'] = df_order['order_delivered_customer_date'] - df_order['order_purchase_timestamp']

df_order['delais_respecter'] = df_order.apply(lambda row: 'oui' if row['order_delivered_customer_date'] < row['order_estimated_delivery_date'] else 'non', axis=1)

df_order = df_order[['order_id', 'customer_id', 'order_status','delai_livraison', 'delais_respecter']]

/var/folders/cq/rtjptvh55mx98pdv787t928w0000gp/T/ipykernel_19270/1653577496.py:19: FutureWarning: Comparison of NaT with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable.
  df_order['delais_respecter'] = df_order.apply(lambda row: 'oui' if row['order_delivered_customer_date'] < row['order_estimated_delivery_date'] else 'non', axis=1)

In [219]:
df_payments =pd.read_csv('archive/olist_order_payments_dataset.csv',low_memory=False)
df_payments=df_payments[['order_id','payment_value']]
df_payments = df_payments.groupby(by='order_id').sum()
df_payments = df_payments.reset_index()
df_payments

                               order_id  payment_value
0      00010242fe8c5a6d1ba2dd792cb16214          72.19
1      00018f77f2f0320c557190d7a144bdd3         259.83
2      000229ec398224ef6ca0657da4fc703e         216.87
3      00024acbcdf0a6daa1e931b038114c75          25.78
4      00042b26cf59d7ce69dfabb4e55b4fd9         218.04
...                                 ...            ...
99435  fffc94f6ce00a00581880bf54a75a037         343.40
99436  fffcd46ef2263f404302a634eb57f7eb         386.53
99437  fffce4705a9662cd70adb13d4a31832d         116.85
99438  fffe18544ffabc95dfada21779c9644f          64.71
99439  fffe41c64501cc87c801fd61db3f6244          55.79

[99440 rows x 2 columns]

In [220]:
df_items =pd.read_csv('archive/olist_order_items_dataset.csv',low_memory=False)
df_items=df_items[['order_id','product_id','seller_id','price','freight_value']]
df_items

,order_id,product_id,seller_id,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,199.90,18.14
...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,43.00,12.79

In [221]:
df_products =pd.read_csv('archive/olist_products_dataset.csv',low_memory=False)
df_products= df_products[['product_id', 'product_category_name']]
df_products

                             product_id              product_category_name
0      1e9e8ef04dbcff4541ed26657ea517e5                         perfumaria
1      3aa071139cb16b67ca9e5dea641aaa2f                              artes
2      96bd76ec8810374ed1b65e291975717f                      esporte_lazer
3      cef67bcfe19066a932b7673e239eb23d                              bebes
4      9dc1a7de274444849c219cff195d0b71              utilidades_domesticas
...                                 ...                                ...
32946  a0b7d5a992ccda646f2d34e418fff5a0                   moveis_decoracao
32947  bf4538d88321d0fd4412a93c974510e6  construcao_ferramentas_iluminacao
32948  9a7c6041fa9592d9d9ef6cfe62a71f8c                    cama_mesa_banho
32949  83808703fc0706a22e264b9d75f04a2e             informatica_acessorios
32950  106392145fca363410d287a815be6de4                    cama_mesa_banho

[32951 rows x 2 columns]

In [222]:
df_traslation =pd.read_csv('archive/product_category_name_translation.csv',low_memory=False)

df_traslation

,product_category_name,product_category_name_english
0,beleza_saude,health_beauty
1,informatica_acessorios,computers_accessories
2,automotivo,auto
3,cama_mesa_banho,bed_bath_table
4,moveis_decoracao,furniture_decor
5,esporte_lazer,sports_leisure
6,perfumaria,perfumery
7,utilidades_domesticas,housewares
8,telefonia,telephony
9,relogios_presentes,watches_gifts
10,alimentos_bebidas,food_drink
11,bebes,baby
12,papelaria,stationery
13,tablets_impressao_imagem,tablets_printing_image
14,brinquedos,toys
15,telefonia_fixa,fixed_telephony
16,ferramentas_jardim,garden_tools
17,fashion_bolsas_e_acessorios,fashion_bags_accessories
18,eletroportateis,small_appliances
19,consoles_games,consoles_games
20,audio,audio
21,fashion_calcados,fashion_shoes
22,cool_stuff,cool_stuff
23,malas_acessorios,luggage_accessories
24,climatizacao,air_conditioning
25,construcao_ferramentas_construcao,construction_tools_construction
26,moveis_cozinha_area_de_servico_jantar_e_jardim,kitchen_dining_laundry_garden_furniture
27,construcao_ferramentas_jardim,costruction_tools_garden
28,fashion_roupa_masculina,fashion_male_clothing
29,pet_shop,pet_shop
30,moveis_escritorio,office_furniture
31,market_place,market_place
32,eletronicos,electronics
33,eletrodomesticos,home_appliances
34,artigos_de_festas,party_supplies
35,casa_conforto,home_confort
36,construcao_ferramentas_ferramentas,costruction_tools_tools
37,agro_industria_e_comercio,agro_industry_and_commerce
38,moveis_colchao_e_estofado,furniture_mattress_and_upholstery
39,livros_tecnicos,books_technical
40,casa_construcao,home_construction
41,instrumentos_musicais,musical_instruments
42,moveis_sala,furniture_living_room
43,construcao_ferramentas_iluminacao,construction_tools_lights
44,industria_comercio_e_negocios,industry_commerce_and_business
45,alimentos,food
46,artes,art
47,moveis_quarto,furniture_bedroom
48,livros_interesse_geral,books_general_interest
49,construcao_ferramentas_seguranca,construction_tools_safety
50,fashion_underwear_e_moda_praia,fashion_underwear_beach
51,fashion_esporte,fashion_sport
52,sinalizacao_e_seguranca,signaling_and_security
53,pcs,computers
54,artigos_de_natal,christmas_supplies
55,fashion_roupa_feminina,fashio_female_clothing
56,eletrodomesticos_2,home_appliances_2
57,livros_importados,books_imported
58,bebidas,drinks
59,cine_foto,cine_photo
60,la_cuisine,la_cuisine
61,musica,music
62,casa_conforto_2,home_comfort_2
63,portateis_casa_forno_e_cafe,small_appliances_home_oven_and_coffee
64,cds_dvds_musicais,cds_dvds_musicals
65,dvds_blu_ray,dvds_blu_ray
66,flores,flowers
67,artes_e_artesanato,arts_and_craftmanship
68,fraldas_higiene,diapers_and_hygiene
69,fashion_roupa_infanto_juvenil,fashion_childrens_clothes
70,seguros_e_servicos,security_and_services

In [223]:
df_seller =pd.read_csv('archive/olist_sellers_dataset.csv',low_memory=False)
df_seller.columns
df_seller =df_seller[['seller_id','seller_state']]
df_seller

                             seller_id seller_state
0     3442f8959a84dea7ee197c632cb2df15           SP
1     d1b65fc7debc3361ea86b5f14c68d2e2           SP
2     ce3ad9de960102d0677a81f5d0bb7b2d           RJ
3     c0f3eea2e14555b6faeea3dd58c1b1c3           SP
4     51a04a8a6bdcb23deccc82b0b80742cf           SP
...                                ...          ...
3090  98dddbc4601dd4443ca174359b237166           PR
3091  f8201cab383e484733266d1906e2fdfa           SC
3092  74871d19219c7d518d0090283e03c137           SP
3093  e603cf3fec55f8697c9059638d6c8eb5           RS
3094  9e25199f6ef7e7c347120ff175652c3b           SP

[3095 rows x 2 columns]

In [224]:
df_reviews =pd.read_csv('archive/olist_order_reviews_dataset.csv',low_memory=False)
df_reviews.columns
df_reviews =df_reviews[['order_id', 'review_score']]
df_reviews

                               order_id  review_score
0      73fc7af87114b39712e6da79b0a377eb             4
1      a548910a1c6147796b98fdf73dbeba33             5
2      f9e4b658b201a9f2ecdecbb34bed034b             5
3      658677c97b385a9be170737859d3511b             5
4      8e6bfb81e283fa7e4f11123a3fb894f1             5
...                                 ...           ...
99219  2a8c23fee101d4d5662fa670396eb8da             5
99220  22ec9f0669f784db00fa86d035cf8602             5
99221  55d4004744368f5571d1f590031933e4             5
99222  7725825d039fc1f0ceb7635e3f7d9206             4
99223  90531360ecb1eec2a1fbb265a0db0508             1

[99224 rows x 2 columns]

In [225]:
df_merged1 = pd.merge(df_order, df_customers, how='left',on='customer_id')
df_merged1

,order_id,customer_id,order_status,delai_livraison,delais_respecter,customer_unique_id,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,8 days,oui,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,14 days,oui,af07308b275d755c9edb36a90c618231,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,9 days,oui,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,14 days,oui,7c142cf63193a1473d2e66489a9ae977,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,3 days,oui,72632f0f9dd73dfee390c9b22eb56dd6,santo andre,SP
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,8 days,oui,6359f309b166b0196dbf7ad2ac62bb5a,sao jose dos campos,SP
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,22 days,oui,da62f9e57a76d978d02ab5362c509660,praia grande,SP
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,25 days,oui,737520a9aad80b3fbbdad19b66b37b30,nova vicosa,BA
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,17 days,oui,5097a5312c8b157bb7be58ae360ef43c,japuiba,RJ
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,8 days,oui,60350aa974b26ff12caad89e55993bd6,lapa,PR

In [226]:
df_merged1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            99441 non-null  object
 1   customer_id         99441 non-null  object
 2   order_status        99441 non-null  object
 3   delai_livraison     96476 non-null  timedelta64[ns]
 4   delais_respecter    99441 non-null  object
 5   customer_unique_id  99441 non-null  object
 6   customer_city       99441 non-null  object
 7   customer_state      99441 non-null  object
dtypes: object(7), timedelta64[ns](1)
memory usage: 6.8+ MB

In [227]:
df_merged2 = pd.merge(df_merged1, df_payments, how='left',on='order_id')
df_merged2

,order_id,customer_id,order_status,delai_livraison,delais_respecter,customer_unique_id,customer_city,customer_state,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,8 days,oui,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,38.71
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,14 days,oui,af07308b275d755c9edb36a90c618231,barreiras,BA,141.46
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,9 days,oui,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO,179.12
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,14 days,oui,7c142cf63193a1473d2e66489a9ae977,sao goncalo do amarante,RN,72.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,3 days,oui,72632f0f9dd73dfee390c9b22eb56dd6,santo andre,SP,28.62
...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,8 days,oui,6359f309b166b0196dbf7ad2ac62bb5a,sao jose dos campos,SP,85.08
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,22 days,oui,da62f9e57a76d978d02ab5362c509660,praia grande,SP,195.00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,25 days,oui,737520a9aad80b3fbbdad19b66b37b30,nova vicosa,BA,271.01
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,17 days,oui,5097a5312c8b157bb7be58ae360ef43c,japuiba,RJ,441.16
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,8 days,oui,60350aa974b26ff12caad89e55993bd6,lapa,PR,86.86

In [228]:
df_merged2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 99441 entries, 0 to 99440
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            99441 non-null  object
 1   customer_id         99441 non-null  object
 2   order_status        99441 non-null  object
 3   delai_livraison     96476 non-null  timedelta64[ns]
 4   delais_respecter    99441 non-null  object
 5   customer_unique_id  99441 non-null  object
 6   customer_city       99441 non-null  object
 7   customer_state      99441 non-null  object
 8   payment_value       99440 non-null  float64
dtypes: float64(1), object(7), timedelta64[ns](1)
memory usage: 7.6+ MB

In [229]:
df_items['order_id'].value_counts()

8272b63d03f5f79c56e9e4120aec44ef    21
1b15974a0141d54e36626dca3fdc731a    20
ab14fdcfbe524636d65ee38360e22ce8    20
9ef13efd6949e4573a18964dd1bbe7f5    15
428a2f660dc84138d969ccd69a0ab6d5    15
                                    ..
5a0911d70c1f85d3bed0df1bf693a6dd     1
5a082b558a3798d3e36d93bfa8ca1eae     1
5a07264682e0b8fbb3f166edbbffc6e8     1
5a071192a28951b76774e5a760c8c9b7     1
fffe41c64501cc87c801fd61db3f6244     1
Name: order_id, Length: 98666, dtype: int64

In [230]:
df_merged3 = pd.merge(df_merged2, df_items, how='left',on='order_id')
df_merged3

,order_id,customer_id,order_status,delai_livraison,delais_respecter,customer_unique_id,customer_city,customer_state,payment_value,product_id,seller_id,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,8 days,oui,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,38.71,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,14 days,oui,af07308b275d755c9edb36a90c618231,barreiras,BA,141.46,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,9 days,oui,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO,179.12,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,14 days,oui,7c142cf63193a1473d2e66489a9ae977,sao goncalo do amarante,RN,72.20,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,3 days,oui,72632f0f9dd73dfee390c9b22eb56dd6,santo andre,SP,28.62,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,19.90,8.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...
113420,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,22 days,oui,da62f9e57a76d978d02ab5362c509660,praia grande,SP,195.00,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,174.90,20.10
113421,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,25 days,oui,737520a9aad80b3fbbdad19b66b37b30,nova vicosa,BA,271.01,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,205.99,65.02
113422,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,17 days,oui,5097a5312c8b157bb7be58ae360ef43c,japuiba,RJ,441.16,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,179.99,40.59
113423,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,17 days,oui,5097a5312c8b157bb7be58ae360ef43c,japuiba,RJ,441.16,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,179.99,40.59
113424,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,8 days,oui,60350aa974b26ff12caad89e55993bd6,lapa,PR,86.86,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,68.50,18.36

In [231]:
df_merged3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 113425 entries, 0 to 113424
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   order_id            113425 non-null  object
 1   customer_id         113425 non-null  object
 2   order_status        113425 non-null  object
 3   delai_livraison     110196 non-null  timedelta64[ns]
 4   delais_respecter    113425 non-null  object
 5   customer_unique_id  113425 non-null  object
 6   customer_city       113425 non-null  object
 7   customer_state      113425 non-null  object
 8   payment_value       113422 non-null  float64
 9   product_id          112650 non-null  object
 10  seller_id           112650 non-null  object
 11  price               112650 non-null  float64
 12  freight_value       112650 non-null  float64
dtypes: float64(3), object(9), timedelta64[ns](1)
memory usage: 12.1+ MB

In [232]:
df_merged4 = pd.merge(df_merged3, df_products, how='left',on='product_id')
df_merged4

,order_id,customer_id,order_status,delai_livraison,delais_respecter,customer_unique_id,customer_city,customer_state,payment_value,product_id,seller_id,price,freight_value,product_category_name
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,8 days,oui,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,38.71,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72,utilidades_domesticas
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,14 days,oui,af07308b275d755c9edb36a90c618231,barreiras,BA,141.46,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,118.70,22.76,perfumaria
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,9 days,oui,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO,179.12,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,159.90,19.22,automotivo
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,14 days,oui,7c142cf63193a1473d2e66489a9ae977,sao goncalo do amarante,RN,72.20,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,45.00,27.20,pet_shop
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,3 days,oui,72632f0f9dd73dfee390c9b22eb56dd6,santo andre,SP,28.62,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,19.90,8.72,papelaria
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113420,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,22 days,oui,da62f9e57a76d978d02ab5362c509660,praia grande,SP,195.00,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,174.90,20.10,bebes
113421,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,25 days,oui,737520a9aad80b3fbbdad19b66b37b30,nova vicosa,BA,271.01,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,205.99,65.02,eletrodomesticos_2
113422,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,17 days,oui,5097a5312c8b157bb7be58ae360ef43c,japuiba,RJ,441.16,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,179.99,40.59,informatica_acessorios
113423,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,17 days,oui,5097a5312c8b157bb7be58ae360ef43c,japuiba,RJ,441.16,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,179.99,40.59,informatica_acessorios
113424,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,8 days,oui,60350aa974b26ff12caad89e55993bd6,lapa,PR,86.86,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,68.50,18.36,beleza_saude

In [233]:
df_merged5 = pd.merge(df_merged4, df_traslation, how='left',on='product_category_name')
df_merged5

,order_id,customer_id,order_status,delai_livraison,delais_respecter,customer_unique_id,customer_city,customer_state,payment_value,product_id,seller_id,price,freight_value,product_category_name,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,8 days,oui,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,38.71,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72,utilidades_domesticas,housewares
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,14 days,oui,af07308b275d755c9edb36a90c618231,barreiras,BA,141.46,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,118.70,22.76,perfumaria,perfumery
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,9 days,oui,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO,179.12,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,159.90,19.22,automotivo,auto
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,14 days,oui,7c142cf63193a1473d2e66489a9ae977,sao goncalo do amarante,RN,72.20,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,45.00,27.20,pet_shop,pet_shop
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,3 days,oui,72632f0f9dd73dfee390c9b22eb56dd6,santo andre,SP,28.62,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,19.90,8.72,papelaria,stationery
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113420,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,22 days,oui,da62f9e57a76d978d02ab5362c509660,praia grande,SP,195.00,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,174.90,20.10,bebes,baby
113421,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,25 days,oui,737520a9aad80b3fbbdad19b66b37b30,nova vicosa,BA,271.01,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,205.99,65.02,eletrodomesticos_2,home_appliances_2
113422,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,17 days,oui,5097a5312c8b157bb7be58ae360ef43c,japuiba,RJ,441.16,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,179.99,40.59,informatica_acessorios,computers_accessories
113423,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,17 days,oui,5097a5312c8b157bb7be58ae360ef43c,japuiba,RJ,441.16,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,179.99,40.59,informatica_acessorios,computers_accessories
113424,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,8 days,oui,60350aa974b26ff12caad89e55993bd6,lapa,PR,86.86,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,68.50,18.36,beleza_saude,health_beauty

In [234]:
df_merged6 = pd.merge(df_merged5, df_seller, how='left',on='seller_id')
df_merged6

,order_id,customer_id,order_status,delai_livraison,delais_respecter,customer_unique_id,customer_city,customer_state,payment_value,product_id,seller_id,price,freight_value,product_category_name,product_category_name_english,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,8 days,oui,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,38.71,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72,utilidades_domesticas,housewares,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,14 days,oui,af07308b275d755c9edb36a90c618231,barreiras,BA,141.46,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,118.70,22.76,perfumaria,perfumery,SP
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,9 days,oui,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO,179.12,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,159.90,19.22,automotivo,auto,SP
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,14 days,oui,7c142cf63193a1473d2e66489a9ae977,sao goncalo do amarante,RN,72.20,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,45.00,27.20,pet_shop,pet_shop,MG
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,3 days,oui,72632f0f9dd73dfee390c9b22eb56dd6,santo andre,SP,28.62,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,19.90,8.72,papelaria,stationery,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113420,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,22 days,oui,da62f9e57a76d978d02ab5362c509660,praia grande,SP,195.00,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,174.90,20.10,bebes,baby,SP
113421,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,25 days,oui,737520a9aad80b3fbbdad19b66b37b30,nova vicosa,BA,271.01,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,205.99,65.02,eletrodomesticos_2,home_appliances_2,SP
113422,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,17 days,oui,5097a5312c8b157bb7be58ae360ef43c,japuiba,RJ,441.16,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,179.99,40.59,informatica_acessorios,computers_accessories,MG
113423,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,17 days,oui,5097a5312c8b157bb7be58ae360ef43c,japuiba,RJ,441.16,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,179.99,40.59,informatica_acessorios,computers_accessories,MG
113424,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,8 days,oui,60350aa974b26ff12caad89e55993bd6,lapa,PR,86.86,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,68.50,18.36,beleza_saude,health_beauty,SP

In [235]:
df_merged7 = pd.merge(df_merged6, df_reviews, how='left',on='order_id')
df_merged7

,order_id,customer_id,order_status,delai_livraison,delais_respecter,customer_unique_id,customer_city,customer_state,payment_value,product_id,seller_id,price,freight_value,product_category_name,product_category_name_english,seller_state,review_score
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,8 days,oui,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,38.71,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,29.99,8.72,utilidades_domesticas,housewares,SP,4.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,14 days,oui,af07308b275d755c9edb36a90c618231,barreiras,BA,141.46,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,118.70,22.76,perfumaria,perfumery,SP,4.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,9 days,oui,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO,179.12,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,159.90,19.22,automotivo,auto,SP,5.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,14 days,oui,7c142cf63193a1473d2e66489a9ae977,sao goncalo do amarante,RN,72.20,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,45.00,27.20,pet_shop,pet_shop,MG,5.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,3 days,oui,72632f0f9dd73dfee390c9b22eb56dd6,santo andre,SP,28.62,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,19.90,8.72,papelaria,stationery,SP,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114087,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,22 days,oui,da62f9e57a76d978d02ab5362c509660,praia grande,SP,195.00,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,174.90,20.10,bebes,baby,SP,4.0
114088,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,25 days,oui,737520a9aad80b3fbbdad19b66b37b30,nova vicosa,BA,271.01,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,205.99,65.02,eletrodomesticos_2,home_appliances_2,SP,5.0
114089,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,17 days,oui,5097a5312c8b157bb7be58ae360ef43c,japuiba,RJ,441.16,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,179.99,40.59,informatica_acessorios,computers_accessories,MG,2.0
114090,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,17 days,oui,5097a5312c8b157bb7be58ae360ef43c,japuiba,RJ,441.16,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,179.99,40.59,informatica_acessorios,computers_accessories,MG,2.0
114091,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,8 days,oui,60350aa974b26ff12caad89e55993bd6,lapa,PR,86.86,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,68.50,18.36,beleza_saude,health_beauty,SP,5.0

In [236]:
df_merged7.columns

Index(['order_id', 'customer_id', 'order_status', 'delai_livraison',
       'delais_respecter', 'customer_unique_id', 'customer_city',
       'customer_state', 'payment_value', 'product_id', 'seller_id', 'price',
       'freight_value', 'product_category_name',
       'product_category_name_english', 'seller_state', 'review_score'],
      dtype='object')

In [237]:
list_to_keep = ['customer_unique_id', 'order_status', 'delai_livraison','delais_respecter','customer_state', 'payment_value','freight_value','product_category_name_english','seller_state', 'review_score']

In [238]:
df=df_merged7[list_to_keep]

In [239]:
df

,customer_unique_id,order_status,delai_livraison,delais_respecter,customer_state,payment_value,freight_value,product_category_name_english,seller_state,review_score
0,7c396fd4830fd04220f754e42b4e5bff,delivered,8 days,oui,SP,38.71,8.72,housewares,SP,4.0
1,af07308b275d755c9edb36a90c618231,delivered,14 days,oui,BA,141.46,22.76,perfumery,SP,4.0
2,3a653a41f6f9fc3d2a113cf8398680e8,delivered,9 days,oui,GO,179.12,19.22,auto,SP,5.0
3,7c142cf63193a1473d2e66489a9ae977,delivered,14 days,oui,RN,72.20,27.20,pet_shop,MG,5.0
4,72632f0f9dd73dfee390c9b22eb56dd6,delivered,3 days,oui,SP,28.62,8.72,stationery,SP,5.0
...,...,...,...,...,...,...,...,...,...,...
114087,da62f9e57a76d978d02ab5362c509660,delivered,22 days,oui,SP,195.00,20.10,baby,SP,4.0
114088,737520a9aad80b3fbbdad19b66b37b30,delivered,25 days,oui,BA,271.01,65.02,home_appliances_2,SP,5.0
114089,5097a5312c8b157bb7be58ae360ef43c,delivered,17 days,oui,RJ,441.16,40.59,computers_accessories,MG,2.0
114090,5097a5312c8b157bb7be58ae360ef43c,delivered,17 days,oui,RJ,441.16,40.59,computers_accessories,MG,2.0
114091,60350aa974b26ff12caad89e55993bd6,delivered,8 days,oui,PR,86.86,18.36,health_beauty,SP,5.0

In [240]:
len(df.columns)

10

In [ ]:
df.to_csv('archive/olist_merge.csv',index=False)