In [62]:
import pandas as pd

# merge des dataframes

In [63]:
def remplacer_par_mode(df):
    mode = df.mode().iloc[0]
    df.fillna(mode, inplace=True)

In [64]:
df_customers = pd.read_csv('archive/olist_customers_dataset.csv',low_memory=False)
df_customers=df_customers[['customer_id', 'customer_unique_id','customer_state']]
df_customers

,customer_id,customer_unique_id,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,SP
...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,SP

In [65]:
df_order =pd.read_csv('archive/olist_orders_dataset.csv',low_memory=False)

mask = df_order['order_status']=='delivered'
df_order=df_order[mask]

df_order

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [66]:
list_colum = ['order_purchase_timestamp',
        'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date']

def transformation_en_date(df,list_colum):
       for col in list_colum:
              df[col] =pd.to_datetime(df[col])
              df[col] = df[col].dt.date
       return df


transformation_en_date(df_order,list_colum)

# df_order['order_status'] = df_order.apply(lambda row: 'delivered' if row['order_status'] =='delivered' else 'no_delivered', axis=1)

df_order['recence'] = df_order['order_purchase_timestamp'].max() - df_order['order_purchase_timestamp']

df_order['delai_livraison'] = df_order['order_delivered_customer_date'] - df_order['order_purchase_timestamp']

df_order['delais_respecter'] = df_order.apply(lambda row: 'oui' if row['order_delivered_customer_date'] < row['order_estimated_delivery_date'] else 'non', axis=1)

remplacer_par_mode(df_order)

df_order['delai_livraison'] = df_order['delai_livraison'].dt.days.astype(int)
df_order['recence'] = df_order['recence'].dt.days.astype(int)

df_order = df_order[['order_id', 'customer_id','recence','delai_livraison', 'delais_respecter']]

df_order

/var/folders/cq/rtjptvh55mx98pdv787t928w0000gp/T/ipykernel_2009/676206076.py:20: FutureWarning: Comparison of NaT with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable.
  df_order['delais_respecter'] = df_order.apply(lambda row: 'oui' if row['order_delivered_customer_date'] < row['order_estimated_delivery_date'] else 'non', axis=1)
/var/folders/cq/rtjptvh55mx98pdv787t928w0000gp/T/ipykernel_2009/40456559.py:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.fillna(mode, inplace=True)

,order_id,customer_id,recence,delai_livraison,delais_respecter
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,331,8,oui
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,36,14,oui
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,21,9,oui
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,284,14,oui
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,197,3,oui
...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,538,8,oui
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,204,22,oui
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,367,25,oui
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,233,17,oui
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,174,8,oui

In [67]:
df_order.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 96478 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          96478 non-null  object
 1   customer_id       96478 non-null  object
 2   recence           96478 non-null  int64
 3   delai_livraison   96478 non-null  int64
 4   delais_respecter  96478 non-null  object
dtypes: int64(2), object(3)
memory usage: 4.4+ MB

In [68]:
df_merged1 = pd.merge(df_order, df_customers, how='left',on='customer_id')
df_merged1

,order_id,customer_id,recence,delai_livraison,delais_respecter,customer_unique_id,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,331,8,oui,7c396fd4830fd04220f754e42b4e5bff,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,36,14,oui,af07308b275d755c9edb36a90c618231,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,21,9,oui,3a653a41f6f9fc3d2a113cf8398680e8,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,284,14,oui,7c142cf63193a1473d2e66489a9ae977,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,197,3,oui,72632f0f9dd73dfee390c9b22eb56dd6,SP
...,...,...,...,...,...,...,...
96473,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,538,8,oui,6359f309b166b0196dbf7ad2ac62bb5a,SP
96474,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,204,22,oui,da62f9e57a76d978d02ab5362c509660,SP
96475,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,367,25,oui,737520a9aad80b3fbbdad19b66b37b30,BA
96476,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,233,17,oui,5097a5312c8b157bb7be58ae360ef43c,RJ
96477,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,174,8,oui,60350aa974b26ff12caad89e55993bd6,PR

In [69]:
df_payments =pd.read_csv('archive/olist_order_payments_dataset.csv',low_memory=False)
df_payments=df_payments[['order_id','payment_installments','payment_value',]]
df_payments = df_payments.groupby('order_id').agg({'payment_value': 'sum','payment_installments': 'sum'})
df_payments = df_payments.reset_index()
df_payments

                               order_id  payment_value  payment_installments
0      00010242fe8c5a6d1ba2dd792cb16214          72.19                     2
1      00018f77f2f0320c557190d7a144bdd3         259.83                     3
2      000229ec398224ef6ca0657da4fc703e         216.87                     5
3      00024acbcdf0a6daa1e931b038114c75          25.78                     2
4      00042b26cf59d7ce69dfabb4e55b4fd9         218.04                     3
...                                 ...            ...                   ...
99435  fffc94f6ce00a00581880bf54a75a037         343.40                     1
99436  fffcd46ef2263f404302a634eb57f7eb         386.53                     1
99437  fffce4705a9662cd70adb13d4a31832d         116.85                     3
99438  fffe18544ffabc95dfada21779c9644f          64.71                     3
99439  fffe41c64501cc87c801fd61db3f6244          55.79                     1

[99440 rows x 3 columns]

In [70]:
df_merged2 = pd.merge(df_merged1, df_payments, how='left',on='order_id')
df_merged2

,order_id,customer_id,recence,delai_livraison,delais_respecter,customer_unique_id,customer_state,payment_value,payment_installments
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,331,8,oui,7c396fd4830fd04220f754e42b4e5bff,SP,38.71,3.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,36,14,oui,af07308b275d755c9edb36a90c618231,BA,141.46,1.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,21,9,oui,3a653a41f6f9fc3d2a113cf8398680e8,GO,179.12,3.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,284,14,oui,7c142cf63193a1473d2e66489a9ae977,RN,72.20,1.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,197,3,oui,72632f0f9dd73dfee390c9b22eb56dd6,SP,28.62,1.0
...,...,...,...,...,...,...,...,...,...
96473,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,538,8,oui,6359f309b166b0196dbf7ad2ac62bb5a,SP,85.08,3.0
96474,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,204,22,oui,da62f9e57a76d978d02ab5362c509660,SP,195.00,3.0
96475,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,367,25,oui,737520a9aad80b3fbbdad19b66b37b30,BA,271.01,5.0
96476,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,233,17,oui,5097a5312c8b157bb7be58ae360ef43c,RJ,441.16,4.0
96477,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,174,8,oui,60350aa974b26ff12caad89e55993bd6,PR,86.86,1.0

In [71]:
df_items =pd.read_csv('archive/olist_order_items_dataset.csv',low_memory=False)
df_items=df_items[['order_id','product_id','seller_id','price','freight_value']]
df_items

,order_id,product_id,seller_id,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,199.90,18.14
...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,43.00,12.79

In [72]:
df_items =pd.read_csv('archive/olist_order_items_dataset.csv',low_memory=False)

df_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [73]:
df_merged3 = pd.merge(df_merged2, df_items, how='left',on='order_id')
df_merged3

,order_id,customer_id,recence,delai_livraison,delais_respecter,customer_unique_id,customer_state,payment_value,payment_installments,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,331,8,oui,7c396fd4830fd04220f754e42b4e5bff,SP,38.71,3.0,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,36,14,oui,af07308b275d755c9edb36a90c618231,BA,141.46,1.0,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,21,9,oui,3a653a41f6f9fc3d2a113cf8398680e8,GO,179.12,3.0,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,284,14,oui,7c142cf63193a1473d2e66489a9ae977,RN,72.20,1.0,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,197,3,oui,72632f0f9dd73dfee390c9b22eb56dd6,SP,28.62,1.0,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110192,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,204,22,oui,da62f9e57a76d978d02ab5362c509660,SP,195.00,3.0,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.90,20.10
110193,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,367,25,oui,737520a9aad80b3fbbdad19b66b37b30,BA,271.01,5.0,1,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.99,65.02
110194,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,233,17,oui,5097a5312c8b157bb7be58ae360ef43c,RJ,441.16,4.0,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59
110195,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,233,17,oui,5097a5312c8b157bb7be58ae360ef43c,RJ,441.16,4.0,2,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59
110196,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,174,8,oui,60350aa974b26ff12caad89e55993bd6,PR,86.86,1.0,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.50,18.36

In [74]:
df_products =pd.read_csv('archive/olist_products_dataset.csv',low_memory=False)
df_products['produit_volume_cm_cube'] = df_products['product_length_cm']*df_products['product_width_cm']*df_products['product_height_cm']
df_products= df_products[['product_id', 'product_category_name','product_weight_g','produit_volume_cm_cube']]

df_products

,product_id,product_category_name,product_weight_g,produit_volume_cm_cube
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,225.0,2240.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,1000.0,10800.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,154.0,2430.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,371.0,2704.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,625.0,4420.0
...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,12300.0,64000.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,1700.0,4864.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,1400.0,5103.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,700.0,8060.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,2083.0,168.0

In [75]:
df_merged4 = pd.merge(df_merged3, df_products, how='left',on='product_id')
df_merged4

,order_id,customer_id,recence,delai_livraison,delais_respecter,customer_unique_id,customer_state,payment_value,payment_installments,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_weight_g,produit_volume_cm_cube
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,331,8,oui,7c396fd4830fd04220f754e42b4e5bff,SP,38.71,3.0,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,500.0,1976.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,36,14,oui,af07308b275d755c9edb36a90c618231,BA,141.46,1.0,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,400.0,4693.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,21,9,oui,3a653a41f6f9fc3d2a113cf8398680e8,GO,179.12,3.0,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,automotivo,420.0,9576.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,284,14,oui,7c142cf63193a1473d2e66489a9ae977,RN,72.20,1.0,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20,pet_shop,450.0,6000.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,197,3,oui,72632f0f9dd73dfee390c9b22eb56dd6,SP,28.62,1.0,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72,papelaria,250.0,11475.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110192,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,204,22,oui,da62f9e57a76d978d02ab5362c509660,SP,195.00,3.0,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.90,20.10,bebes,4950.0,16000.0
110193,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,367,25,oui,737520a9aad80b3fbbdad19b66b37b30,BA,271.01,5.0,1,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.99,65.02,eletrodomesticos_2,13300.0,63360.0
110194,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,233,17,oui,5097a5312c8b157bb7be58ae360ef43c,RJ,441.16,4.0,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59,informatica_acessorios,6550.0,8000.0
110195,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,233,17,oui,5097a5312c8b157bb7be58ae360ef43c,RJ,441.16,4.0,2,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59,informatica_acessorios,6550.0,8000.0
110196,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,174,8,oui,60350aa974b26ff12caad89e55993bd6,PR,86.86,1.0,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.50,18.36,beleza_saude,150.0,1680.0

In [76]:
df_traslation =pd.read_csv('archive/product_category_name_translation.csv',low_memory=False)

df_traslation

            product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao               furniture_decor
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns]

In [77]:
df_merged5 = pd.merge(df_merged4, df_traslation, how='left',on='product_category_name')
df_merged5

,order_id,customer_id,recence,delai_livraison,delais_respecter,customer_unique_id,customer_state,payment_value,payment_installments,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_weight_g,produit_volume_cm_cube,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,331,8,oui,7c396fd4830fd04220f754e42b4e5bff,SP,38.71,3.0,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,500.0,1976.0,housewares
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,36,14,oui,af07308b275d755c9edb36a90c618231,BA,141.46,1.0,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,400.0,4693.0,perfumery
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,21,9,oui,3a653a41f6f9fc3d2a113cf8398680e8,GO,179.12,3.0,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,automotivo,420.0,9576.0,auto
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,284,14,oui,7c142cf63193a1473d2e66489a9ae977,RN,72.20,1.0,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20,pet_shop,450.0,6000.0,pet_shop
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,197,3,oui,72632f0f9dd73dfee390c9b22eb56dd6,SP,28.62,1.0,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72,papelaria,250.0,11475.0,stationery
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110192,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,204,22,oui,da62f9e57a76d978d02ab5362c509660,SP,195.00,3.0,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.90,20.10,bebes,4950.0,16000.0,baby
110193,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,367,25,oui,737520a9aad80b3fbbdad19b66b37b30,BA,271.01,5.0,1,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.99,65.02,eletrodomesticos_2,13300.0,63360.0,home_appliances_2
110194,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,233,17,oui,5097a5312c8b157bb7be58ae360ef43c,RJ,441.16,4.0,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59,informatica_acessorios,6550.0,8000.0,computers_accessories
110195,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,233,17,oui,5097a5312c8b157bb7be58ae360ef43c,RJ,441.16,4.0,2,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59,informatica_acessorios,6550.0,8000.0,computers_accessories
110196,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,174,8,oui,60350aa974b26ff12caad89e55993bd6,PR,86.86,1.0,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.50,18.36,beleza_saude,150.0,1680.0,health_beauty

In [78]:
df_seller =pd.read_csv('archive/olist_sellers_dataset.csv',low_memory=False)
df_seller.columns
df_seller =df_seller[['seller_id','seller_state']]
df_seller

                             seller_id seller_state
0     3442f8959a84dea7ee197c632cb2df15           SP
1     d1b65fc7debc3361ea86b5f14c68d2e2           SP
2     ce3ad9de960102d0677a81f5d0bb7b2d           RJ
3     c0f3eea2e14555b6faeea3dd58c1b1c3           SP
4     51a04a8a6bdcb23deccc82b0b80742cf           SP
...                                ...          ...
3090  98dddbc4601dd4443ca174359b237166           PR
3091  f8201cab383e484733266d1906e2fdfa           SC
3092  74871d19219c7d518d0090283e03c137           SP
3093  e603cf3fec55f8697c9059638d6c8eb5           RS
3094  9e25199f6ef7e7c347120ff175652c3b           SP

[3095 rows x 2 columns]

In [79]:
df_merged6 = pd.merge(df_merged5, df_seller, how='left',on='seller_id')
df_merged6

,order_id,customer_id,recence,delai_livraison,delais_respecter,customer_unique_id,customer_state,payment_value,payment_installments,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_weight_g,produit_volume_cm_cube,product_category_name_english,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,331,8,oui,7c396fd4830fd04220f754e42b4e5bff,SP,38.71,3.0,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,500.0,1976.0,housewares,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,36,14,oui,af07308b275d755c9edb36a90c618231,BA,141.46,1.0,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,400.0,4693.0,perfumery,SP
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,21,9,oui,3a653a41f6f9fc3d2a113cf8398680e8,GO,179.12,3.0,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,automotivo,420.0,9576.0,auto,SP
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,284,14,oui,7c142cf63193a1473d2e66489a9ae977,RN,72.20,1.0,1,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20,pet_shop,450.0,6000.0,pet_shop,MG
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,197,3,oui,72632f0f9dd73dfee390c9b22eb56dd6,SP,28.62,1.0,1,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72,papelaria,250.0,11475.0,stationery,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110192,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,204,22,oui,da62f9e57a76d978d02ab5362c509660,SP,195.00,3.0,1,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.90,20.10,bebes,4950.0,16000.0,baby,SP
110193,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,367,25,oui,737520a9aad80b3fbbdad19b66b37b30,BA,271.01,5.0,1,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.99,65.02,eletrodomesticos_2,13300.0,63360.0,home_appliances_2,SP
110194,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,233,17,oui,5097a5312c8b157bb7be58ae360ef43c,RJ,441.16,4.0,1,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59,informatica_acessorios,6550.0,8000.0,computers_accessories,MG
110195,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,233,17,oui,5097a5312c8b157bb7be58ae360ef43c,RJ,441.16,4.0,2,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59,informatica_acessorios,6550.0,8000.0,computers_accessories,MG
110196,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,174,8,oui,60350aa974b26ff12caad89e55993bd6,PR,86.86,1.0,1,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.50,18.36,beleza_saude,150.0,1680.0,health_beauty,SP

In [80]:
df_reviews =pd.read_csv('archive/olist_order_reviews_dataset.csv',low_memory=False)
df_reviews.columns
df_reviews =df_reviews[['order_id', 'review_score']]
df_reviews

                               order_id  review_score
0      73fc7af87114b39712e6da79b0a377eb             4
1      a548910a1c6147796b98fdf73dbeba33             5
2      f9e4b658b201a9f2ecdecbb34bed034b             5
3      658677c97b385a9be170737859d3511b             5
4      8e6bfb81e283fa7e4f11123a3fb894f1             5
...                                 ...           ...
99219  2a8c23fee101d4d5662fa670396eb8da             5
99220  22ec9f0669f784db00fa86d035cf8602             5
99221  55d4004744368f5571d1f590031933e4             5
99222  7725825d039fc1f0ceb7635e3f7d9206             4
99223  90531360ecb1eec2a1fbb265a0db0508             1

[99224 rows x 2 columns]

In [81]:
df_merged7 = pd.merge(df_merged6, df_reviews, how='left',on='order_id')
df_merged7

,order_id,customer_id,recence,delai_livraison,delais_respecter,customer_unique_id,customer_state,payment_value,payment_installments,order_item_id,...,seller_id,shipping_limit_date,price,freight_value,product_category_name,product_weight_g,produit_volume_cm_cube,product_category_name_english,seller_state,review_score
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,331,8,oui,7c396fd4830fd04220f754e42b4e5bff,SP,38.71,3.0,1,...,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,utilidades_domesticas,500.0,1976.0,housewares,SP,4.0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,36,14,oui,af07308b275d755c9edb36a90c618231,BA,141.46,1.0,1,...,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,perfumaria,400.0,4693.0,perfumery,SP,4.0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,21,9,oui,3a653a41f6f9fc3d2a113cf8398680e8,GO,179.12,3.0,1,...,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,automotivo,420.0,9576.0,auto,SP,5.0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,284,14,oui,7c142cf63193a1473d2e66489a9ae977,RN,72.20,1.0,1,...,66922902710d126a0e7d26b0e3805106,2017-11-23 19:45:59,45.00,27.20,pet_shop,450.0,6000.0,pet_shop,MG,5.0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,197,3,oui,72632f0f9dd73dfee390c9b22eb56dd6,SP,28.62,1.0,1,...,2c9e548be18521d1c43cde1c582c6de8,2018-02-19 20:31:37,19.90,8.72,papelaria,250.0,11475.0,stationery,SP,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110835,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,204,22,oui,da62f9e57a76d978d02ab5362c509660,SP,195.00,3.0,1,...,1f9ab4708f3056ede07124aad39a2554,2018-02-12 13:10:37,174.90,20.10,bebes,4950.0,16000.0,baby,SP,4.0
110836,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,367,25,oui,737520a9aad80b3fbbdad19b66b37b30,BA,271.01,5.0,1,...,d50d79cb34e38265a8649c383dcffd48,2017-09-05 15:04:16,205.99,65.02,eletrodomesticos_2,13300.0,63360.0,home_appliances_2,SP,5.0
110837,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,233,17,oui,5097a5312c8b157bb7be58ae360ef43c,RJ,441.16,4.0,1,...,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59,informatica_acessorios,6550.0,8000.0,computers_accessories,MG,2.0
110838,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,233,17,oui,5097a5312c8b157bb7be58ae360ef43c,RJ,441.16,4.0,2,...,a1043bafd471dff536d0c462352beb48,2018-01-12 21:36:21,179.99,40.59,informatica_acessorios,6550.0,8000.0,computers_accessories,MG,2.0
110839,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,174,8,oui,60350aa974b26ff12caad89e55993bd6,PR,86.86,1.0,1,...,ececbfcff9804a2d6b40f589df8eef2b,2018-03-15 10:55:42,68.50,18.36,beleza_saude,150.0,1680.0,health_beauty,SP,5.0

In [82]:
df_merged7.columns

Index(['order_id', 'customer_id', 'recence', 'delai_livraison',
       'delais_respecter', 'customer_unique_id', 'customer_state',
       'payment_value', 'payment_installments', 'order_item_id', 'product_id',
       'seller_id', 'shipping_limit_date', 'price', 'freight_value',
       'product_category_name', 'product_weight_g', 'produit_volume_cm_cube',
       'product_category_name_english', 'seller_state', 'review_score'],
      dtype='object')

In [83]:
list_to_keep = ['customer_unique_id','order_id', 'recence', 'delai_livraison',
       'delais_respecter', 'customer_state',
       'payment_value', 'payment_installments',
       'price', 'freight_value', 'product_weight_g',
       'produit_volume_cm_cube', 'product_category_name_english',
       'seller_state', 'review_score']

In [84]:
df=df_merged7[list_to_keep]

df

,customer_unique_id,order_id,recence,delai_livraison,delais_respecter,customer_state,payment_value,payment_installments,price,freight_value,product_weight_g,produit_volume_cm_cube,product_category_name_english,seller_state,review_score
0,7c396fd4830fd04220f754e42b4e5bff,e481f51cbdc54678b7cc49136f2d6af7,331,8,oui,SP,38.71,3.0,29.99,8.72,500.0,1976.0,housewares,SP,4.0
1,af07308b275d755c9edb36a90c618231,53cdb2fc8bc7dce0b6741e2150273451,36,14,oui,BA,141.46,1.0,118.70,22.76,400.0,4693.0,perfumery,SP,4.0
2,3a653a41f6f9fc3d2a113cf8398680e8,47770eb9100c2d0c44946d9cf07ec65d,21,9,oui,GO,179.12,3.0,159.90,19.22,420.0,9576.0,auto,SP,5.0
3,7c142cf63193a1473d2e66489a9ae977,949d5b44dbf5de918fe9c16f97b45f8a,284,14,oui,RN,72.20,1.0,45.00,27.20,450.0,6000.0,pet_shop,MG,5.0
4,72632f0f9dd73dfee390c9b22eb56dd6,ad21c59c0840e6cb83a9ceb5573f8159,197,3,oui,SP,28.62,1.0,19.90,8.72,250.0,11475.0,stationery,SP,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110835,da62f9e57a76d978d02ab5362c509660,63943bddc261676b46f01ca7ac2f7bd8,204,22,oui,SP,195.00,3.0,174.90,20.10,4950.0,16000.0,baby,SP,4.0
110836,737520a9aad80b3fbbdad19b66b37b30,83c1379a015df1e13d02aae0204711ab,367,25,oui,BA,271.01,5.0,205.99,65.02,13300.0,63360.0,home_appliances_2,SP,5.0
110837,5097a5312c8b157bb7be58ae360ef43c,11c177c8e97725db2631073c19f07b62,233,17,oui,RJ,441.16,4.0,179.99,40.59,6550.0,8000.0,computers_accessories,MG,2.0
110838,5097a5312c8b157bb7be58ae360ef43c,11c177c8e97725db2631073c19f07b62,233,17,oui,RJ,441.16,4.0,179.99,40.59,6550.0,8000.0,computers_accessories,MG,2.0
110839,60350aa974b26ff12caad89e55993bd6,66dea50a8b16d9b4dee7af250b4be1a5,174,8,oui,PR,86.86,1.0,68.50,18.36,150.0,1680.0,health_beauty,SP,5.0

# diminution de categorie

In [85]:
category_map = {'housewares': 'Home and Decor',
                'perfumery': 'Fashion and Beauty',
                'auto': 'Electronics and Technology',
                'pet_shop': 'Other',
                'stationery': 'Leisure and Entertainment',
                'furniture_decor': 'Home and Decor',
                'office_furniture': 'Other',
                'garden_tools': 'Tools and Construction',
                'computers_accessories': 'Electronics and Technology',
                'bed_bath_table': 'Home and Decor',
                'toys': 'Leisure and Entertainment',
                'construction_tools_construction': 'Tools and Construction',
                'telephony': 'Electronics and Technology',
                'health_beauty': 'Health and Beauty',
                'electronics': 'Electronics and Technology',
                'baby': 'Health and Beauty',
                'cool_stuff': 'Leisure and Entertainment',
                'watches_gifts': 'Leisure and Entertainment',
                'air_conditioning': 'Home and Decor',
                'sports_leisure': 'Leisure and Entertainment',
                'books_General_interest': 'Leisure and Entertainment',
                'small_appliances': 'Home and Decor',
                'food': 'Food and Beverage',
                'luggage_accessories': 'Fashion and Beauty',
                'fashion_underwear_beach': 'Fashion and Beauty',
                'christmas_supplies': 'Leisure and Entertainment',
                'fashion_bags_accessories': 'Fashion and Beauty',
                'musical_instruments': 'Leisure and Entertainment',
                'construction_tools_lights': 'Tools and Construction',
                'books_technical': 'Leisure and Entertainment',
                'costruction_tools_garden': 'Tools and Construction',
                'home_appliances': 'Home and Decor',
                'market_place': 'Other',
                'agro_industry_and_commerce': 'Other',
                'party_supplies': 'Leisure and Entertainment',
                'home_confort': 'Home and Decor',
                'cds_dvds_musicals': 'Leisure and Entertainment',
                'industry_commerce_and_business': 'Other',
                'consoles_games': 'Leisure and Entertainment',
                'furniture_bedroom': 'Home and Decor',
                'construction_tools_safety': 'Tools and Construction',
                'fixed_telephony': 'Electronics and Technology',
                'drinks': 'Food and Beverage',
                'kitchen_dining_laundry_garden_furniture': 'Home and Decor',
                'fashion_shoes': 'Fashion and Beauty',
                'home_construction': 'Tools and Construction',
                'audio': 'Electronics and Technology',
                'home_appliances_2': 'Home and Decor',
                'fashion_male_clothing': 'Fashion and Beauty',
                'cine_photo': 'Electronics and Technology',
                'furniture_living_room': 'Home and Decor',
                'art': 'Leisure and Entertainment',
                'food_drink': 'Food and Beverage'}
df['category']=df['product_category_name_english'].map(category_map,)

/var/folders/cq/rtjptvh55mx98pdv787t928w0000gp/T/ipykernel_2009/1623818227.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['category']=df['product_category_name_english'].map(category_map,)

# remplacer par la mode

In [86]:
mode = df.mode().iloc[0]
df.fillna(mode, inplace=True)
df.isna().sum()

/var/folders/cq/rtjptvh55mx98pdv787t928w0000gp/T/ipykernel_2009/3350974138.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(mode, inplace=True)

customer_unique_id               0
order_id                         0
recence                          0
delai_livraison                  0
delais_respecter                 0
customer_state                   0
payment_value                    0
payment_installments             0
price                            0
freight_value                    0
product_weight_g                 0
produit_volume_cm_cube           0
product_category_name_english    0
seller_state                     0
review_score                     0
category                         0
dtype: int64

# ajouter des colonne

In [87]:
df['seller_in_state']=df.apply(lambda row: 'oui' if row['customer_state'] < row['seller_state'] else 'non', axis=1)

/var/folders/cq/rtjptvh55mx98pdv787t928w0000gp/T/ipykernel_2009/677323970.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['seller_in_state']=df.apply(lambda row: 'oui' if row['customer_state'] < row['seller_state'] else 'non', axis=1)

In [88]:
df=df.drop(['product_category_name_english','seller_state'],axis=1)

In [89]:
df

,customer_unique_id,order_id,recence,delai_livraison,delais_respecter,customer_state,payment_value,payment_installments,price,freight_value,product_weight_g,produit_volume_cm_cube,review_score,category,seller_in_state
0,7c396fd4830fd04220f754e42b4e5bff,e481f51cbdc54678b7cc49136f2d6af7,331,8,oui,SP,38.71,3.0,29.99,8.72,500.0,1976.0,4.0,Home and Decor,non
1,af07308b275d755c9edb36a90c618231,53cdb2fc8bc7dce0b6741e2150273451,36,14,oui,BA,141.46,1.0,118.70,22.76,400.0,4693.0,4.0,Fashion and Beauty,oui
2,3a653a41f6f9fc3d2a113cf8398680e8,47770eb9100c2d0c44946d9cf07ec65d,21,9,oui,GO,179.12,3.0,159.90,19.22,420.0,9576.0,5.0,Electronics and Technology,oui
3,7c142cf63193a1473d2e66489a9ae977,949d5b44dbf5de918fe9c16f97b45f8a,284,14,oui,RN,72.20,1.0,45.00,27.20,450.0,6000.0,5.0,Other,non
4,72632f0f9dd73dfee390c9b22eb56dd6,ad21c59c0840e6cb83a9ceb5573f8159,197,3,oui,SP,28.62,1.0,19.90,8.72,250.0,11475.0,5.0,Leisure and Entertainment,non
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110835,da62f9e57a76d978d02ab5362c509660,63943bddc261676b46f01ca7ac2f7bd8,204,22,oui,SP,195.00,3.0,174.90,20.10,4950.0,16000.0,4.0,Health and Beauty,non
110836,737520a9aad80b3fbbdad19b66b37b30,83c1379a015df1e13d02aae0204711ab,367,25,oui,BA,271.01,5.0,205.99,65.02,13300.0,63360.0,5.0,Home and Decor,oui
110837,5097a5312c8b157bb7be58ae360ef43c,11c177c8e97725db2631073c19f07b62,233,17,oui,RJ,441.16,4.0,179.99,40.59,6550.0,8000.0,2.0,Electronics and Technology,non
110838,5097a5312c8b157bb7be58ae360ef43c,11c177c8e97725db2631073c19f07b62,233,17,oui,RJ,441.16,4.0,179.99,40.59,6550.0,8000.0,2.0,Electronics and Technology,non
110839,60350aa974b26ff12caad89e55993bd6,66dea50a8b16d9b4dee7af250b4be1a5,174,8,oui,PR,86.86,1.0,68.50,18.36,150.0,1680.0,5.0,Health and Beauty,oui

In [90]:
df_grouped = df.groupby(['customer_unique_id', 'order_id', 'recence', 'delai_livraison',
       'delais_respecter', 'customer_state', 'payment_value',
       'payment_installments','review_score', 'category',
       'seller_in_state']).agg({'price': 'sum', 
                                'freight_value': 'sum', 
                                'produit_volume_cm_cube': 'sum', 
                                'product_weight_g': 'sum'})

In [91]:
df =df_grouped.reset_index()

In [92]:
len(df.columns)

15

In [93]:
df=df.drop('payment_value',axis=1)

In [94]:
freq = df.groupby('customer_unique_id')['order_id'].nunique()
df['freq_achat'] = df['customer_unique_id'].map(freq)

In [95]:
df.columns

Index(['customer_unique_id', 'order_id', 'recence', 'delai_livraison',
       'delais_respecter', 'customer_state', 'payment_installments',
       'review_score', 'category', 'seller_in_state', 'price', 'freight_value',
       'produit_volume_cm_cube', 'product_weight_g', 'freq_achat'],
      dtype='object')

In [97]:
grouped_df = df.groupby(['customer_unique_id','freq_achat']) .agg({'delais_respecter': lambda x: x.value_counts().index[0],
                    'seller_in_state': lambda x: x.value_counts().index[0],
                    'customer_state': lambda x: x.value_counts().index[0],
                    'recence': 'mean',
                    'delai_livraison': 'mean',
                    'payment_installments': 'mean',
                    'review_score': 'mean',
                    'category': lambda x: x.value_counts().index[0],
                    'price': 'mean',
                    'freight_value': 'mean',
                    'produit_volume_cm_cube': 'mean',
                    'product_weight_g': 'mean'})

In [98]:
df = grouped_df.reset_index()

In [99]:
df['customer_unique_id'].value_counts()

0000366f3b9a7992bf8c76cfdf3221e2    1
aa798bd609e98391c373f1f0f9102e3f    1
aa789d52aed60d7a80bfbbadd9e9ba13    1
aa7853ce070036b66ac47b1d98f3cf3d    1
aa7658e197aca5c7932cf21de7b48fd3    1
                                   ..
5528e8c8cdfa15940d89eb1d21866350    1
5528af7e794d044322ea7fc8cde9a086    1
5527213e610f0a189308f8e404b3a88f    1
55259a97665208d40d62b5a26f9f0915    1
ffffd2657e2aad2907e67c3e9daecbeb    1
Name: customer_unique_id, Length: 93358, dtype: int64

In [101]:
df['freq_achat'].value_counts()

1     90557
2      2573
3       181
4        28
5         9
6         5
7         3
9         1
15        1
Name: freq_achat, dtype: int64

In [102]:
df.to_csv('archive/olist_merge.csv',index=False)
df

,customer_unique_id,freq_achat,delais_respecter,seller_in_state,customer_state,recence,delai_livraison,payment_installments,review_score,category,price,freight_value,produit_volume_cm_cube,product_weight_g
0,0000366f3b9a7992bf8c76cfdf3221e2,1,oui,non,SP,111.0,6.0,8.0,5.0,Home and Decor,129.90,12.00,7616.0,1500.0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,1,oui,non,SP,114.0,3.0,1.0,4.0,Health and Beauty,18.90,8.29,5148.0,375.0
2,0000f46a3911fa3c0805444483337064,1,oui,oui,SC,537.0,26.0,8.0,3.0,Leisure and Entertainment,69.00,17.22,43750.0,1500.0
3,0000f6ccb0745a6a4b88665a16c9f078,1,oui,oui,PA,321.0,20.0,4.0,4.0,Electronics and Technology,25.99,17.63,1045.0,150.0
4,0004aac84e0df4da2b147fca70cf8255,1,oui,non,SP,288.0,13.0,6.0,5.0,Electronics and Technology,180.00,16.89,528.0,6050.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93353,fffcf5a5ff07b0908bd4e2dbc735a684,1,oui,oui,PE,447.0,28.0,10.0,5.0,Health and Beauty,1570.00,497.42,503250.0,60000.0
93354,fffea47cd6d3cc0a88bd621562a9d061,1,oui,oui,BA,262.0,30.0,1.0,4.0,Health and Beauty,64.89,19.69,32076.0,1720.0
93355,ffff371b4d645b6ecea244b27531430a,1,oui,non,MT,568.0,15.0,1.0,5.0,Electronics and Technology,89.90,22.56,3315.0,600.0
93356,ffff5962728ec6157033ef9805bacc48,1,oui,oui,ES,119.0,12.0,5.0,5.0,Leisure and Entertainment,115.00,18.69,4480.0,444.0
93357,ffffd2657e2aad2907e67c3e9daecbeb,1,oui,oui,PR,484.0,8.0,4.0,5.0,Fashion and Beauty,56.99,14.57,2178.0,400.0